general {
  no_fade_in = false
  grace = 0 
  disable_loading_bar = false
  dpms_off = true
}

background {
  color=rgb(1f1f28)
  path=/home/tbsl/Pictures/.hyprlock/background/wallhaven_silksong.png
}

# Digital Clock (Hours & Minutes)
label {
    monitor =
    text = $TIME
    font_size = 80
    font_family = DejaVu Sans
    color = rgb(dcd7ba)
    position = 0, 180
    halign = center
    valign = center
}

# Date Sub-label
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    font_size = 20
    font_family = DejaVu Sans
    color = rgb(c0a36e)
    position = 0, 110
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.3
    fade_on_empty = false
    check_color = rgb(c0a36e)
    fail_color = rgb(c34043)
    font_color = rgb(dcd7ba)
    inner_color = rgb(1f1f28)
    outer_color = rgb(54547d)
    position = 0, -20
    halign = center
    valign = center
}
